Feature/latest message bubble
Cognigy/WebchatWidget pull request #127
Opened 2020-10-22 14:37 UTC by AlexTeusz

This feature request added the following features to the webchat:

1. Show badge with number of unseen bot messages
2. Show the lastest unseen bot message as a bubble next to the toggle button

**Example:**
![](https://alexteusz.s3-eu-west-1.amazonaws.com/cognigy/demofiles/Bildschirmfoto+2020-10-22+um+16.34.24.png)

2020-10-27 13:02 UTC, mastasky approved these changes
Functional Review OK

2020-10-28 09:41 UTC, pedily commented
This PR adds the concept of unssen messages
a message is unseen if a message arrives when either the webchat is closed or the tab is in the background
we added some features that can help users be aware of unread messages
- we added a badge that shows the number of unread messages at the toggle button
- we added a preview bubble that shows the text of the last message at the toggle button
- we added a notification sound that plays when unread messages arrive
- we added a title indicator that can be used to change the title of the page with an unread counter + a text

2020-10-28 13:28 UTC, kwinto commented
If an unread message contains no extractable text, it should not hide the previous message preview.

An example:
- bot sends text message: "Just look at this cutie";
- bot sends a picture of a kitten;
It make sense to keep the first message preview instead of showing nothing as we currently do.

2020-10-28 13:41 UTC, kwinto commented
Flashing page title indicator it pretty invasive. It would be nice to have an option to add unread message counter to the beginning of current page title without replacing/flashing it.

2020-10-28 13:52 UTC, kwinto commented on src/webchat-ui/components/presentational/Badge.tsx
> +            <span style={{
Inline styles make it hard to customise. Also should provide a stable class name string for customisations.

2020-10-28 13:55 UTC, kwinto commented
Sound notification does not work in Safari Desktop

2020-10-28 14:03 UTC, kwinto commented on docs/embedding.md
> +| enableUnreadMessagePreview | boolean | false | | | If true, the webchat shows a message bubble with the latest retreived bot message.
>retreived

2020-10-28 14:25 UTC, kwinto commented
code looks good, please see the comment above

2020-10-28 17:00 UTC, mastasky commented on docs/embedding.md
> +| enableUnreadMessagePreview | boolean | false | | | If true, the webchat shows a message bubble with the latest retreived bot message.
fixed

2020-10-28 17:11 UTC, mastasky requested changes
Message persistent can throw these features off.

1. Reload Issue
Get the webchat to display a preview and badge in closed mode.
Reload the page.
Badge is gone.
Click button.
Windows flashes and badge is back (wrongly)

2. Tab Change
Click something in the chat that will show messages
Quickly move to another tab
Messages come in and you see the title bar notification
Close the tab
Re-open a new tab with webchat url
Webchat is closed, open it. You will now hear sounds and badge shows
You must go to another tab and return to fix it

2020-10-29 16:39 UTC, pedily commented
@mastasky issue 1 is fixed. the "open: false" state was restored on connect (the "open" event caused the connect!). The webchat will now stay open if it was open before

2020-10-29 16:54 UTC, pedily commented
the other issue is also fixed

2020-10-29 22:59 UTC, mastasky commented
Please make sure it say this:

(1) New Message
(2) New Messages

2020-10-30 07:51 UTC, mastasky commented
> Please make sure it say this:
> 
> (1) New Message
> (2) New Messages

Built in

2020-10-30 07:52 UTC, mastasky approved these changes
lgtm

2020-10-30 10:36 UTC, pedily approved these changes

2020-10-30 10:57 UTC, merged