(re-)store only relevant information from storage
Cognigy/WebchatWidget pull request #137
Opened 2020-12-01 10:02 UTC by kwinto

This PR changes what we store and restore for the "persistence history" mechanism to the local (-session) storage
- it is only the "messages" now.

Also fixes storing duplicate data with an empty keys (["","",""]) in storage.

To test: 
initialize the webchat with a fixed sessionId string and test it behaves normally, also with these endpoint settings:
                    `getStartedText: "INJECT",
                    startBehavior: "injection"`
and these:
                    `disablePersistentHistory: true,
                    engagementMessageText: "Hi!",
                    engagementMessageDelay: 500`

2020-12-09 16:48 UTC, dshire requested changes
You also need to keep the ui.open state, else the chat closes on a multi-page website implementation when switching the page

2020-12-09 17:58 UTC, kwinto commented
> You also need to keep the ui.open state, else the chat closes on a multi-page website implementation when switching the page

You mean this is reproducible on this branch? The partial saved state is being merged here, therefore it should actually be independent.

2020-12-15 09:11 UTC, dshire approved these changes

2020-12-15 09:24 UTC, dshire commented
as discussed the "open" state is not stored in localstorage any longer and only the messages are. this is working fine with these changes so I approved.

2020-12-16 08:39 UTC, sushmi21 approved these changes

2020-12-16 08:44 UTC, merged