Improve UX on connection lost
Cognigy/WebchatWidget pull request #155
Opened 2021-03-01 20:37 UTC by kwinto

This PR fixes three problems rooting in reconnection attempt limit.

1. In Safari and Chrome leaving the connected Webchat in an inactive tab for some time would eventually result in the socket connection drop. Webchat would then try to reestablish the connection and fail. After the user would switch back to the tab, he would be unable to interact with the application. He would see the banner suggesting to reload the page.

This is now fixed by restarting connection right after the tab is active again.

2. If the user would go offline, and the Webchat had been connected before, user would see a banner "Lost connection" and a suggestion to reload the page. 

This is now fixed by restarting connection right after the browser reports network is reachable again.

3. As the second method is not always reliable (we may be connected to some network but have no access to internet) we will again rich the connection attempts limit and see the banner "reload the page".

This is now improved by showing a button "Press to connect" instead.

Test steps:
tbd

2021-03-05 13:47 UTC, pedily commented
Spamming "connect" actions doesn't have a negative influence on the reconnection behavior.

2021-03-05 13:49 UTC, pedily commented
The visual style of the "reconnect button" is a bit off.
The label should be less verbose and just say "retry".
When you click it, it should disappear and the "reconnecting" text should be shown again.
The button shape should be like the "submit" button in a date picker (primary color, font style etc).

2021-03-05 13:50 UTC, pedily commented
I was not able to use the "reconnect" button, it had no visible effect for me (i scaled down my endpoint, waited until the webchat "gave up", scaled up again, and pressed the button, nothing happened (button still there, no indicator, the text did not change)

2021-03-05 13:50 UTC, pedily requested changes
The style of the "reconnect button" should be changed.

The "reconnect button" seemed to have no effect for me.

2021-03-05 16:50 UTC, kwinto commented on src/webchat/store/connection/connection-middleware.ts
> +        }
No, it will first dispatch a lock "isConnecting". If locked, no connection attempts are made.

2021-05-18 12:01 UTC, dshire requested changes
Two things:
1. There is no UX indication that the system actually tries to reconnect when clicking change when clicking the "Reconnect" button. There should be text indications like "Reconnecting..." "Reconnecting failed" etc. to provide the user with more information.
2. The functionality changes after I reconnected once using the "reconnect" button. From then on, I always immediately see this button, and not the automatic reconnection mechanic. I would expect that it starts again with the automatic reconnection once a connection had been established again

2021-06-04 07:50 UTC, kwinto commented
> 1. There is no UX indication that the system actually tries to reconnect when clicking change when clicking the "Reconnect" button. There should be text indications like "Reconnecting..." "Reconnecting failed" etc. to provide the user with more information.

The way it works now is very close to what you get in a browser when trying to open a page with internet connection down. I would leave it as is.

> 2. The functionality changes after I reconnected once using the "reconnect" button. From then on, I always immediately see this button, and not the automatic reconnection mechanic. I would expect that it starts again with the automatic reconnection once a connection had been established again

This should be fixed now.

2021-06-04 07:52 UTC, kwinto commented
> The style of the "reconnect button" should be changed.
> The "reconnect button" seemed to have no effect for me.

Was fixed a while ago, please review again

2021-07-13 14:31 UTC, pedily approved these changes

2021-07-13 15:29 UTC, dshire approved these changes

2021-07-13 15:30 UTC, merged