Scroll card with focused button into view
Cognigy/WebchatWidget pull request #165
Opened 2021-03-31 17:31 UTC by sushmi21

When you have gallery cards with buttons, you will be able to focus the buttons in the cards using tab. Sometimes, when the button in the card receives focus, the card will not be scrolled to the middle (Example: When you have three cards with at least one button each, when a button in card 2 receives focus, the card will not be scrolled to middle). Hence, you will be able to see only half of the focused button and the card in which it is present. 
With this fix, the button inside the card that is focused will be scrolled into view. Additionally, the button groups are assigned aria-labelledby and aria-describedby attributed

To test:
- Create gallery with multiple cards and add at at least one button to each card 
- Navigate using keyboard and see if the focused button is fully visible

2021-04-01 11:45 UTC, kwinto approved these changes
ie11 ✔️

2021-04-06 15:48 UTC, Cesarcs7 approved these changes

2021-04-08 08:33 UTC, dshire requested changes
working as expected, there's just some typos you should fix before we merge

2021-04-08 08:33 UTC, dshire commented on src/plugins/messenger/MessengerPreview/components/MessengerGenericTemplate/MessengerGenericTemplate.tsx
> +            const carousalRootId = `webchat-carousel-template-root-${uuid.v4()}`;
typo *carousel

2021-04-08 08:33 UTC, dshire commented on src/plugins/messenger/MessengerPreview/components/MessengerGenericTemplate/MessengerGenericTemplate.tsx
> +            const carousalAriaDescribedBy = document.getElementById(carouselSubtitle) ? carouselSubtitle : undefined;
also typo *carousel

2021-04-08 08:58 UTC, sushmi21 commented on src/plugins/messenger/MessengerPreview/components/MessengerGenericTemplate/MessengerGenericTemplate.tsx
> +            const carousalRootId = `webchat-carousel-template-root-${uuid.v4()}`;
fixed

2021-04-08 08:58 UTC, sushmi21 commented on src/plugins/messenger/MessengerPreview/components/MessengerGenericTemplate/MessengerGenericTemplate.tsx
> +            const carousalAriaDescribedBy = document.getElementById(carouselSubtitle) ? carouselSubtitle : undefined;
fixed

2021-04-08 09:01 UTC, dshire approved these changes

2021-04-08 09:06 UTC, merged