Focus input field after clicking postback or quick reply
Cognigy/WebchatWidget pull request #199
Opened 2021-07-21 17:37 UTC by sushmi21

This PR adds a new feature flag which when true will move focus to the input field after a quick reply or a post back button is clicked.

To test: 
- Use a flow that has quick reply buttons and postback buttons.
- In index.html, set `focusInputAfterPostback: true`
- In the chat, if you now click postback or quick reply button, focus will move to input text.
- Change the flag to false and see if the focus doesn't change

2021-07-22 12:23 UTC, cbuchwald approved these changes

2021-07-22 15:21 UTC, dshire requested changes
Works fine for must buttons etc. but not for buttons on gallery cards. as these are also postback values, it should work the same

2021-07-22 15:52 UTC, sushmi21 commented
> Works fine for must buttons etc. but not for buttons on gallery cards. as these are also postback values, it should work the same

Fixed. Thanks!

2021-07-23 07:14 UTC, dshire approved these changes
lgtm

2021-07-23 07:14 UTC, merged