feature/20846 upgrade webpack
Cognigy/WebchatWidget pull request #235
Opened 2022-01-03 12:51 UTC by cbuchwald

Updated packages and modified build scripts.

How to test:

1. npm run build
2. Test if everything works as before
3. Open two terminals with "npm run cypress:serve" and "npm run cypress:open" to test if everything still works

2022-01-04 08:13 UTC, EgleHelms approved these changes
Spec files are running well. Crated webchat.js file usable.

2022-01-04 13:45 UTC, pedily commented
Why did you switch to individual webpack configuration files per service?
If we want to keep it that way, I would suggest to move them into a subfolder (like we have for Dockerfiles in build-utils) and change the naming to `webpack.plugin-name.js` and `webpack.plugin-name.legacy.js`

2022-01-04 14:46 UTC, pedily commented
the legacy build outputs contain ES6 features like arrow functions and do not run in IE11

2022-01-04 14:47 UTC, pedily requested changes

2022-01-04 16:52 UTC, cbuchwald commented on package.json
> +    "date-picker": "webpack --config webpack.production-plugin.date-picker.js --entry ./src/plugins/date-picker/index.tsx",
Ok, will move it

2022-01-04 17:07 UTC, cbuchwald commented
> Why did you switch to individual webpack configuration files per service? If we want to keep it that way, I would suggest to move them into a subfolder (like we have for Dockerfiles in build-utils) and change the naming to `webpack.plugin-name.js` and `webpack.plugin-name.legacy.js`

With Webpack 5 we no longer have the --output flag, therefore we need to have two files for each plugin and unfortunately it's not possible to move them to another folder, I already tried.

2022-01-04 17:08 UTC, cbuchwald commented
> the legacy build outputs contain ES6 features like arrow functions and do not run in IE11

Thanks, that's a good catch, will see how I can fix this!

2022-01-04 20:43 UTC, cbuchwald commented on package.json
> +    "date-picker": "webpack --config webpack.production-plugin.date-picker.js --entry ./src/plugins/date-picker/index.tsx",
moved

2022-01-06 11:58 UTC, pedily commented
i checked compatibility for the legacy build with all the browsers we mention on our github page and it works

2022-01-06 12:02 UTC, pedily approved these changes

2022-01-06 12:20 UTC, merged