Feature/26013 focus trap for non popover webchat
Cognigy/WebchatWidget pull request #269
Opened 2022-05-11 16:41 UTC by sushmi21

Implement Focus trap even if the both close chat buttons(Close Toggle button and close button in chat header) are absent.

**Success Criteria:**
- When `enableFocusTrap` setting is set to true, the keyboard focus should always not leave the chat window under the following conditions:
1. Even when the 'Rating' button is present or absent in webchat header.
2. Even if the 'Persistent Menu' button is present or absent to the left of the text input field.
3. Even when the 'Send message' button is enabled or disabled.
4. Even if there is 'Get started' button instead of the Text field.
5. Even when 'Close' button is present or absent in webchat header.
6. Even if the 'Chat toggle' button is present or absent.

**How to test:**
1. Enable `enableFocusTrap` setting in webchat and navigate the webchat using TAB and SHIFT+TAB keys
2. Test the success criteria 1 to 4 by enabling/ disabling the individual feature in the webchat settings
3. Success criteria 5 and 6 can be tested by removing the Close/Chat toggle button in the code

2022-05-16 07:40 UTC, sushmi21 commented
I will add new tests after my other PR (https://github.com/Cognigy/WebchatWidget/pull/271) gets merged.

2022-05-16 07:40 UTC, sushmi21 commented
I will add new tests after my other PR (https://github.com/Cognigy/WebchatWidget/pull/271) gets merged.

2022-05-18 08:31 UTC, pedily requested changes

2022-05-19 07:09 UTC, sushmi21 commented on src/webchat-ui/utils/find-focusable.ts
> +	const webchatWindow = document.getElementById("webchatWindow");
Fixed

2022-05-19 11:02 UTC, pedily approved these changes

2022-05-19 11:02 UTC, merged