Feature/56237 fix tests
Cognigy/WebchatWidget pull request #380
Opened 2024-02-27 08:15 UTC by sushmi21

This PR fixes the remaining failing webchat tests

2024-02-29 18:59 UTC, fabclj commented
It looks good to me, just a issue about the 2 ratings tests currently failing. It is expected? If it something related to upcoming changes, I would suggest to disable them temporary.

2024-02-29 19:00 UTC, fabclj requested changes
It looks good to me, just a issue about the 2 ratings tests currently failing. It is expected? If it something related to upcoming changes, I would suggest to disable them temporary.

2024-03-01 08:09 UTC, sushmi21 commented
> It looks good to me, just a issue about the 2 ratings tests currently failing. It is expected? If it something related to upcoming changes, I would suggest to disable them temporary.

It is because I merged v3 into this branch yesterday evening. I will check and fix these tests.

2024-03-01 08:45 UTC, fabclj approved these changes

2024-03-01 09:23 UTC, merged